# Generated by Django 4.0.10 on 2023-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tasks', models.ManyToManyField(to='tasks.task')),
            ],
            options={
                'verbose_name': 'Tasks List',
                'verbose_name_plural': 'Tasks Lists',
            },
        ),
    ]
